#!/usr/bin/env python3
"""Cargo.lock に対応する配布用ライセンス文書を生成・検証する。"""

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "THIRD_PARTY_NOTICES.md"
REGISTRY = "registry+https://github.com/rust-lang/crates.io-index"
LICENSE_PREFIXES = ("license", "licence", "copying", "copyright", "notice", "unlicense")


def cargo(*args):
    return subprocess.check_output(
        ["cargo"] + list(args), cwd=str(ROOT), encoding="utf-8"
    )


def release_packages(metadata):
    tree = cargo(
        "tree",
        "--locked",
        "--target",
        "all",
        "--edges",
        "normal,build",
        "--prefix",
        "none",
        "--format",
        "{p}",
        "--color",
        "never",
    )
    keys = {tuple(line.split()[:2]) for line in tree.splitlines() if line.strip()}
    packages = {(p["name"], "v" + p["version"]): p for p in metadata["packages"]}
    if not keys.issubset(packages):
        raise ValueError("cargo tree と metadata の依存関係が一致しません")
    return sorted(
        (
            packages[key]
            for key in keys
            if packages[key]["id"] not in metadata["workspace_members"]
        ),
        key=lambda p: (p["name"], p["version"]),
    )


def license_files(package, metadata):
    root = Path(package["manifest_path"]).parent
    paths = {
        p
        for p in root.rglob("*")
        if p.is_file() and p.name.lower().startswith(LICENSE_PREFIXES)
    }
    if package["license_file"]:
        paths.add(root / package["license_file"])
    files = [
        (str(p.relative_to(root)), p.read_text(encoding="utf-8")) for p in sorted(paths)
    ]

    # 0.4.0 の import library パッケージは上流共通 LICENSE を梱包し忘れている。
    if not files and (package["name"], package["version"]) in {
        ("winapi-i686-pc-windows-gnu", "0.4.0"),
        ("winapi-x86_64-pc-windows-gnu", "0.4.0"),
    }:
        upstream = next(
            p
            for p in metadata["packages"]
            if p["name"] == "winapi"
            and p["version"] == "0.3.9"
            and p["source"] == REGISTRY
        )
        path = Path(upstream["manifest_path"]).parent / "LICENSE-MIT"
        files = [
            (
                "winapi-rs 0.3.9 / LICENSE-MIT (shared upstream license)",
                path.read_text(encoding="utf-8"),
            )
        ]
    if not files or any(not content.strip() for _, content in files):
        raise ValueError(
            "ライセンス本文が不足しています: "
            + package["name"]
            + " "
            + package["version"]
        )
    return [
        (name, "\n".join(line.rstrip(" \t") for line in content.split("\n")))
        for name, content in files
    ]


def generate():
    metadata = json.loads(cargo("metadata", "--locked", "--format-version", "1"))
    packages = release_packages(metadata)
    digest = hashlib.sha256((ROOT / "Cargo.lock").read_bytes()).hexdigest()
    lines = [
        "# Third-party notices",
        "",
        "zsh-turbo itself is licensed under the MIT License; see LICENSE.",
        "Dependencies retain their own licenses and copyright notices.",
        "",
        "Generated by `python3 scripts/licenses.py` from Cargo.lock.",
        "Scope: default features, normal and build dependencies, all target platforms.",
        "Development-only and inactive optional dependencies are excluded.",
        "The list is a superset of the dependencies linked into any one supported binary.",
        "Identical license documents are reproduced once, with references from each package.",
        "OR (and the legacy / notation) denotes alternative licenses; AND denotes combined terms.",
        "Reproducing alternative license texts does not turn OR into AND.",
        "",
        "Cargo.lock SHA-256: `{}`".format(digest),
        "",
        "## MPL source availability",
        "",
        "This distribution uses the unmodified option-ext library under MPL-2.0.",
        "Its version-specific source archive is linked in the package table below;",
        "that source remains available under MPL-2.0, whose full text is reproduced here.",
        "The MIT license for zsh-turbo does not replace or restrict those rights.",
        "",
        "## Font",
        "",
        "MesloLGS NF is downloaded separately and is not included in the release archive.",
        "Its upstream attribution and Apache-2.0 terms are in licenses/MesloLGS-NF.txt.",
        "The installer also saves these terms beside the fonts.",
        "",
        "## Packages ({})".format(len(packages)),
        "",
        "The source archive links contain the exact published crate versions used by Cargo.lock.",
        "The two winapi GNU import-library crates omit license files from their archives;",
        "their shared upstream MIT license is reproduced from winapi 0.3.9:",
        "https://github.com/retep998/winapi-rs/blob/0.3.9/LICENSE-MIT",
        "",
        "| Package | Declared license | Source archive | License and notice documents |",
        "| --- | --- | --- | --- |",
    ]
    documents = {}
    for package in packages:
        if package["source"] != REGISTRY:
            raise ValueError(
                "crates.io 以外の依存には出典の確認が必要です: " + package["name"]
            )
        if not package["license"]:
            raise ValueError("ライセンス宣言がありません: " + package["name"])
        refs = []
        for filename, content in license_files(package, metadata):
            if content not in documents:
                documents[content] = len(documents) + 1
            number = documents[content]
            refs.append("[{}](#document-{})".format(filename, number))
        name, version = package["name"], package["version"]
        source = "https://static.crates.io/crates/{0}/{0}-{1}.crate".format(
            name, version
        )
        lines.append(
            "| {} {} | {} | [source]({}) | {} |".format(
                name, version, package["license"], source, "; ".join(refs)
            )
        )
    lines.extend(["", "## License and notice texts", ""])
    for content, number in documents.items():
        fence = "````"
        while fence in content:
            fence += "`"
        lines.extend(
            [
                "### Document {}".format(number),
                "",
                fence + "text",
                content.rstrip("\n"),
                fence,
                "",
            ]
        )
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="生成せず差分がないか検証する"
    )
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            sys.exit(
                "THIRD_PARTY_NOTICES.md が古いか存在しません。make licenses を実行してください。"
            )
        print("THIRD_PARTY_NOTICES.md: up to date")
    else:
        OUTPUT.write_text(content, encoding="utf-8")
        print("Generated THIRD_PARTY_NOTICES.md")


if __name__ == "__main__":
    main()
